export const NEXT: any = {
    "race": [
        {
            "cid": "242",
            "country": "England",
            "mid": "3059",
            "meeting": "Plumpton",
            "tp": "GL",
            "id": "20871",
            "title": "Sky Sports Racing Launching January 2019 Handicap Chase",
            "number": "5",
            "date": "2018-11-19T14:30:00",
            "st": "5",
            "ss": "AP",
            "tris": "0",
            "prize": "461400",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "4344",
            "weather": "Overcast",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "203",
            "country": "South Africa",
            "mid": "3055",
            "meeting": "Fairview",
            "tp": "GL",
            "id": "20844",
            "title": "Tab Pays The Full Dividend, No Limits Fm 70 Handicap (F & M)",
            "number": "7",
            "date": "2018-11-19T14:40:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "4499400",
            "prize_currency": "ZAR",
            "distance_units": "yards",
            "distance": "1312",
            "weather": "Cloudy",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "242",
            "country": "England",
            "mid": "3057",
            "meeting": "Hereford",
            "tp": "GL",
            "id": "20856",
            "title": "attheraces.com Handicap Hurdle",
            "number": "5",
            "date": "2018-11-19T14:45:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "623800",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "3573",
            "weather": "Fine & Sunny",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "242",
            "country": "England",
            "mid": "3059",
            "meeting": "Plumpton",
            "tp": "GL",
            "id": "20872",
            "title": "Free Tips Daily On attheraces.com Handicap Chase",
            "number": "6",
            "date": "2018-11-19T15:05:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "461400",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "6262",
            "weather": "Overcast",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "203",
            "country": "South Africa",
            "mid": "3055",
            "meeting": "Fairview",
            "tp": "GL",
            "id": "20845",
            "title": "Next Fairview Race Meeting Is Friday 23 November Mr 66 Handicap",
            "number": "8",
            "date": "2018-11-19T15:15:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "4124800",
            "prize_currency": "ZAR",
            "distance_units": "yards",
            "distance": "1094",
            "weather": "Cloudy",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "242",
            "country": "England",
            "mid": "3057",
            "meeting": "Hereford",
            "tp": "GL",
            "id": "20857",
            "title": "Major Bar Handicap Chase",
            "number": "6",
            "date": "2018-11-19T15:20:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "461400",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "5544",
            "weather": "Fine & Sunny",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "242",
            "country": "England",
            "mid": "3059",
            "meeting": "Plumpton",
            "tp": "GL",
            "id": "20873",
            "title": "Watch Today's Race Replays On attheraces.com Handicap Hurdle",
            "number": "7",
            "date": "2018-11-19T15:35:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "311900",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "5497",
            "weather": "Overcast",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "242",
            "country": "England",
            "mid": "3057",
            "meeting": "Hereford",
            "tp": "GL",
            "id": "20858",
            "title": "photodesign.co.uk Novices' Hurdle",
            "number": "7",
            "date": "2018-11-19T15:50:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "409400",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "3573",
            "weather": "Fine & Sunny",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "242",
            "country": "England",
            "mid": "3045",
            "meeting": "Kempton",
            "tp": "GL",
            "id": "20732",
            "title": "Bet At racinguk.com Fillies' Novice Auction Stakes (Plus 10)",
            "number": "1",
            "date": "2018-11-19T16:00:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "388100",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "1320",
            "weather": "Unsettled",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "242",
            "country": "England",
            "mid": "3045",
            "meeting": "Kempton",
            "tp": "GL",
            "id": "20733",
            "title": "32Red On The App Store Novice Stakes",
            "number": "2",
            "date": "2018-11-19T16:30:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "388100",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "2639",
            "weather": "Unsettled",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "242",
            "country": "England",
            "mid": "3045",
            "meeting": "Kempton",
            "tp": "GL",
            "id": "20734",
            "title": "32Red Casino Handicap",
            "number": "3",
            "date": "2018-11-19T17:00:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "646900",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "1540",
            "weather": "Unsettled",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "202",
            "country": "USA",
            "mid": "3064",
            "meeting": "Finger Lakes",
            "tp": "GL",
            "id": "20900",
            "title": "Race 1 - Stakes",
            "number": "1",
            "date": "2018-11-19T17:15:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "1575000",
            "prize_currency": "USD",
            "distance_units": "yards",
            "distance": "1760",
            "weather": "",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "202",
            "country": "USA",
            "mid": "3066",
            "meeting": "Mahoning Valley",
            "tp": "GL",
            "id": "20919",
            "title": "Race 1 - Maiden Special Weight",
            "number": "1",
            "date": "2018-11-19T17:20:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "1864800",
            "prize_currency": "USD",
            "distance_units": "yards",
            "distance": "1210",
            "weather": "",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "242",
            "country": "England",
            "mid": "3045",
            "meeting": "Kempton",
            "tp": "GL",
            "id": "20735",
            "title": "100% Profit Boost At 32RedSport.com Handicap",
            "number": "4",
            "date": "2018-11-19T17:30:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "933800",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "1760",
            "weather": "Unsettled",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "202",
            "country": "USA",
            "mid": "3064",
            "meeting": "Finger Lakes",
            "tp": "GL",
            "id": "20901",
            "title": "Race 2 - Claiming",
            "number": "2",
            "date": "2018-11-19T17:42:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "567000",
            "prize_currency": "USD",
            "distance_units": "yards",
            "distance": "1320",
            "weather": "",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "202",
            "country": "USA",
            "mid": "3066",
            "meeting": "Mahoning Valley",
            "tp": "GL",
            "id": "20920",
            "title": "Race 2 - Allowance",
            "number": "2",
            "date": "2018-11-19T17:48:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "1971900",
            "prize_currency": "USD",
            "distance_units": "yards",
            "distance": "1760",
            "weather": "",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "242",
            "country": "England",
            "mid": "3045",
            "meeting": "Kempton",
            "tp": "GL",
            "id": "20736",
            "title": "32Red London Middle Distance Series Final Handicap",
            "number": "5",
            "date": "2018-11-19T18:00:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "4668800",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "2419",
            "weather": "Unsettled",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "202",
            "country": "USA",
            "mid": "3064",
            "meeting": "Finger Lakes",
            "tp": "GL",
            "id": "20902",
            "title": "Race 3 - Maiden Special Weight",
            "number": "3",
            "date": "2018-11-19T18:09:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "1449000",
            "prize_currency": "USD",
            "distance_units": "yards",
            "distance": "1830",
            "weather": "",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "202",
            "country": "USA",
            "mid": "3066",
            "meeting": "Mahoning Valley",
            "tp": "GL",
            "id": "20921",
            "title": "Race 3 - Claiming",
            "number": "3",
            "date": "2018-11-19T18:16:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "1052100",
            "prize_currency": "USD",
            "distance_units": "yards",
            "distance": "1210",
            "weather": "",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        },
        {
            "cid": "242",
            "country": "England",
            "mid": "3045",
            "meeting": "Kempton",
            "tp": "GL",
            "id": "20737",
            "title": "32Red.com Handicap",
            "number": "6",
            "date": "2018-11-19T18:30:00",
            "st": "1",
            "ss": "AP",
            "tris": "0",
            "prize": "646900",
            "prize_currency": "GBP",
            "distance_units": "yards",
            "distance": "3518",
            "weather": "Unsettled",
            "pers": {
                "tot": "0",
                "qf": "1",
                "ss": "AP"
            }
        }
    ]
}